### ISSUE TITLE
Unable to get MorphemeAttribute from other plugins

### ISSUE THREAD

**Issue by kazuma-t** [WorksApplications/elasticsearch-sudachi#101]
We are trying to provide a filter for Sudachi analysis results in another plugin. While the unit test passes successfully, We are unable to get the `MorphemeAttribute` on Es. The following error message is displayed:

```
"type" : "illegal_state_exception",
"reason" : "Attribute MorphemeAttribute was not present"
```

To resolve this issue, it is necessary for the `AnalysisSudachiPlugin` to inherit from the `ExtensiblePlugin`.

**Comment by eiennohito** [comment]
Fixed by #103
