### ISSUE TITLE
異なる split_mode を併用する方法について

### ISSUE THREAD

**Issue by ackintosh** [WorksApplications/elasticsearch-sudachi#133]
@mh-northlander @kazuma-t 

素晴らしいプラグインの開発をありがとうございます。

https://github.com/WorksApplications/elasticsearch-sudachi/issues/75 に関連してご質問させてください。
[こちら](https://github.com/WorksApplications/elasticsearch-sudachi/issues/75#issuecomment-2134190251)のコメントで、dis_maxを利用してAモードとCモードを併用する例を示していただいています。

```json
    "query": {
        "dis_max": { "queries": [
            { "match": {
                "sentence": {
                    "query": "${text}",
                    "analyzer": "sudachi_a"
                }
            }},
            { "match": {
                "sentence": {
                    "query": "${text}",
                    "analyzer": "sudachi_c"
                }
            }}
        ]}
    },
```

「AモードとCモードで高い方のスコアが使われる」という挙動になると理解しています。これは以前 sudachi_split を検索時に利用できていた時の挙動と一致するものでしょうか？

背景として、**sudachi_split を検索時に利用できていた時の挙動を再現したい**という事情がありまして、ご質問させていただきました。

**Comment by mh-northlander** [comment]
上記の `dis_max` を用いた例の結果は sudachi_split を用いたものとは一致しません。
sudachi_split の挙動の完全な再現は難しいです。

`sudachi_tokenizer` のみで `match` クエリを作成した場合、最終的に構成されるクエリは分割後の各語を `bool` クエリの `should` 節に並べたものに等しくなり、sudachi_split を用いた場合は再分割が行われた部分**のみ**が `match_phrase` クエリの形でそれぞれ追加される形になるようです。

このためトークナイザーを複数使用する場合、下記のように bool - should を用いる形が `dis_max` より近い結果になるかと思いますが、以下の点で差分が発生します。
- A/B 単位に分割される部分についてフレーズクエリ（ひとまとまり）にならない
- 分割されない部分は重複して計上される

これらの差分を完全に解消することはできないのではと思います。

```
"query": {
    "bool": { "should": [
        {"match": {
            "sentence": {
                "query": "${text}",
                "analyzer": "custom_c"
            }
        }},
        {"match": {
            "sentence": {
                "query": "${text}",
                "analyzer": "custom_a"
            }
        }}
    ]}
}
```

なお限定的ですが、「クエリテキスト全体が Sudachi の一語である（かつA/B単位の分割を持つ）」場合は上記の A 単位側を `match_phrase` クエリにすることで sudachi_split を再現できます。

**Comment by ackintosh** [comment]
@mh-northlander 詳細に解説いただきありがとうございます。

> `sudachi_tokenizer` のみで `match` クエリを作成した場合、最終的に構成されるクエリは分割後の各語を `bool` クエリの `should` 節に並べたものに等しくなり、sudachi_split を用いた場合は再分割が行われた部分**のみ**が `match_phrase` クエリの形でそれぞれ追加される形になるようです。

最終的に構成されるクエリを私なりに具体例で整理すると下記になるのですが相違ございますでしょうか？ 🙏 

例：医薬品安全管理責任者
- C単位：医薬品 / 安全 / 管理責任者
- A単位：医薬 / 品 / 安全 / 管理 / 責任 / 者


```json
"query": {
  "bool": {
    "should": [
      ## C単位で分割した各語
      {
        "match": {
          "sentence": {
            "query": "医薬品",
            "analyzer": "custom_C"
          }
        }
      },
      {
        "match": {
          "sentence": {
            "query": "安全",
            "analyzer": "custom_C"
          }
        }
      },
      {
        "match": {
          "sentence": {
            "query": "管理責任者",
            "analyzer": "custom_C"
          }
        }
      },
      ## A単位で再分割が行われる "医薬品" "管理責任者" を match_phrase で追加
      {
        "match_phrase": {
          "sentence": {
            "query": "医薬品",
            "analyzer": "custom_A"
          }
        }
      },
      {
        "match_phrase": {
          "sentence": {
            "query": "管理責任者",
            "analyzer": "custom_A"
          }
        }
      }
    ]
  }
}
```

**Comment by mh-northlander** [comment]
はい、そうなります
`explain: true` をクエリパラメーターに付与して実行すると、内部のスコア付けの詳細も（順序は前後しますが）一致することが確認できると思います

**Comment by ackintosh** [comment]
ありがとうございます！
クローズさせていただきます。
