### ISSUE TITLE
offsets for string array conflict each other

### ISSUE THREAD

**Issue by higu0shin** [WorksApplications/elasticsearch-sudachi#25]
Version : es 6.2.2

### When I indexed string array fields and analyzed them with sudachi, error below occurred. 

`{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=8,lastStartOffset=2 for field 'tags.analyze'"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=8,lastStartOffset=2 for field 'tags.analyze'"
  },
  "status": 400
}`

===============================
It seems to be a bug.
Here is the result of testing with analyze API

**REQUEST**
`GET test/_analyze
{
  "text": ["オフセットがおかしい","オフセットが重複している"],
  "field": "field.sudachi"
}`

**RESPONSE**
`{
  "tokens": [
    {
      "token": "オフセット",
      "start_offset": 0,
      "end_offset": 5,
      "type": "word",
      "position": 0
    },
    {
      "token": "おかしい",
      "start_offset": 6,
      "end_offset": 10,
      "type": "word",
      "position": 2
    },
    {
      "token": "オフセット",
      "start_offset": 1,
      "end_offset": 6,
      "type": "word",
      "position": 103
    },
    {
      "token": "重複",
      "start_offset": 7,
      "end_offset": 9,
      "type": "word",
      "position": 105
    }
  ]
}
`

Thanks.

**Comment by kazuma-t** [comment]
This problem happens to me. I'll check it.
