### ISSUE TITLE
Build Tests failed due to encoding issue under Japanese Win10

### ISSUE THREAD

**Issue by li-hon** [WorksApplications/elasticsearch-sudachi#34]
Under Japanese Windows10, when running `mvn package`, building was successful but build tests would fail due to encoding issue.

The error message is like below:
```
[ERROR] testReadSentencesComma(com.worksap.nlp.lucene.sudachi.ja.TestSudachiTokenizer)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: oovPOS is invalid:名▒?,普通名▒?,▒?般,*,*,*
        at com.worksap.nlp.lucene.sudachi.ja.TestSudachiTokenizer.setup(TestSudachiTokenizer.java:60)
```

However, I got build success under Japanese Ubuntu virtual machine. I tried several things and finally found a temporary solution.

Solution:
1. delete old building files or re-clone this repo.
2. Change the encoding of the file `elasticsearch-sudachi\src\test\resources\com\worksap\nlp\lucene\sudachi\ja\sudachi.json` to `CP932`.
3. run `mvn package`

**Comment by liu-to** [comment]
Bug fixed by https://github.com/WorksApplications/elasticsearch-sudachi/pull/46
