### ISSUE TITLE
Support ElasticSearch 8.3

### ISSUE THREAD

**Issue by eiennohito** [WorksApplications/elasticsearch-sudachi#91]
8.3 once more have changed analysis plugin internal APIs, so it needs some work to support

**Comment by helloes1985** [comment]
8.4.1のsudachi pluginを作成してから以下の問題がありました
①8.2.2で"ナイキ"の形態素解析結果はナイキです、8.4.1の形態素解析結果はナイにしまった
②上記の原因を調査して、_analyzeのexplain=trueを追加して、詳細な形態素解析結果をみるとき、以下エラーが発生した
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "cannot write xcontent for unknown value of type class com.worksap.nlp.sudachi.MorphemeImpl"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "cannot write xcontent for unknown value of type class com.worksap.nlp.sudachi.MorphemeImpl",
        "suppressed": [
            {
                "type": "illegal_state_exception",
                "reason": "Failed to close the XContentBuilder",
                "caused_by": {
                    "type": "i_o_exception",
                    "reason": "Unclosed object or array found"
                }
            }
        ]
    },
    "status": 400
}
ご確認いただけませんか
