### ISSUE TITLE
Migrating plugin to work with OpenSearch

### ISSUE THREAD

**Issue by abseth-amzn** [WorksApplications/elasticsearch-sudachi#95]
Requesting support for building the sudachi analysis plugin with OpenSearch to enable its installation on OpenSearch clusters.
Some helpful links -
* https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md
* https://github.com/aparo/elasticsearch-opensearch-migration-scripts
* https://github.com/soosinha/opensearch-analysis-ik/commit/4a34e1e7f96098e5b93d2562086f643916c16abf

**Comment by eiennohito** [comment]
I will use this issue as a tracking issue for OpenSearch support.

**Comment by eiennohito** [comment]
Now works in OpenSearch (locally).
