### ISSUE TITLE
Can not install the plugin

### ISSUE THREAD

**Issue by maxwill9457** [WorksApplications/elasticsearch-sudachi#99]
Hi,
I tried to install the sudachi plugin to my Elasticsearch cluster on Elastic cloud. However, kibana failed to restart once I add the plugin into it.
So my also tried to install the plugin v3.0.1 and v3.0.0  to my local Elasticsearch v8.5.3 on windows PC, but got following error,
Is there any ideal to solve it? 

----------------------------------------------------------------------
D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin>elasticsearch-plugin install D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Installing D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Downloading D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Failed installing D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Rolling back D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Rolled back D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
Exception in thread "main" java.net.MalformedURLException: unknown protocol: d
        at java.base/java.net.URL.<init>(URL.java:682)
        at java.base/java.net.URL.<init>(URL.java:570)
        at java.base/java.net.URL.<init>(URL.java:517)
        at org.elasticsearch.plugins.cli.InstallPluginAction.downloadZip(InstallPluginAction.java:458)
        at org.elasticsearch.plugins.cli.InstallPluginAction.download(InstallPluginAction.java:329)
        at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:247)
        at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.Command.main(Command.java:50)
        at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)

D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin>

----------------------------------------------------------------------
Best regards

**Comment by kazuma-t** [comment]
Hello,

The "elasticsearch-plugin install" command takes a URL as an argument, so if you want to specify a file directly, you need to express it using the file protocol. In your case, you can modify your command like this:

```bash
elasticsearch-plugin install file:///D:/00Data/dev/dev/elasticsearch-8.5.3-windows-x86_64/elasticsearch-8.5.3/bin/analysis-sudachi-8.5.3-3.0.0.zip
```

By adding "file:///" at the beginning of the file path, you are telling Elasticsearch to look for the plugin locally on your Windows PC.

**Comment by maxwill9457** [comment]
@kazuma-t 
It works! Thank you so much!

-> Installing file:///D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
-> Downloading file:///D:\00Data\dev\dev\elasticsearch-8.5.3-windows-x86_64\elasticsearch-8.5.3\bin\analysis-sudachi-8.5.3-3.0.0.zip
[=================================================] 100%??
-> Installed analysis-sudachi
-> Please restart Elasticsearch to activate any plugins installed


Now I can focus on my Elastic Cloud deployment issue.
I got one question is that is this plugin appliable to Elasticsearch on Elastic Cloud? 
Because I couldn't find any information on the internet.

To my understand, since Elastic cloud also use the same version of Elasticsearch, so theoretically Sudachi plugin is appliable, However, Elastic cloud provides UI to do the installation, so it would be Elastic cloud's issue, am I correct?
 
 Best regard

**Comment by kazuma-t** [comment]
I'm not familiar with Elastic Cloud at all, but it looks like you can't install third-party plugins at the moment.

**Comment by maxwill9457** [comment]
Hi, Thanks for the support.
I have solved the problem to use sudachi on Elastic cloud deployment.

Here is the way that how I install sudachi plugin.
1) Add the sudachi plugin "analysis-sudachi-8.5.3-3.0.1.zip" to Elastic cloud through extensions GUI
2) Add the dictionay "system_core.dic" to Elastic cloud through extensions GUI with zip file in following file structure
    ※This step is the main reason about the install faliure

    dictionaries.zip
     .				
    └	 dictionaries			
     　	└ sudachi		
	　	　　└ system_core.dic	
3) Add both extensions in 1 and 2  into Elasticsearch Deployment and restart 

Done!
